//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2cmi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMIEntities : DbContext
    {
        public CMIEntities()
            : base("name=CMIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMI> CMI { get; set; }
        public virtual DbSet<Indicador> Indicador { get; set; }
        public virtual DbSet<Indicador_Datos> Indicador_Datos { get; set; }
        public virtual DbSet<Meta> Meta { get; set; }
        public virtual DbSet<Objetivo> Objetivo { get; set; }
        public virtual DbSet<Perspectiva> Perspectiva { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
    }
}
