//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2cmi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMIDBContext : DbContext
    {
        public CMIDBContext()
            : base("name=CMIDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMI> CMIs { get; set; }
        public virtual DbSet<Indicador> Indicadors { get; set; }
        public virtual DbSet<Indicador_Datos> Indicador_Datos { get; set; }
        public virtual DbSet<Meta> Metas { get; set; }
        public virtual DbSet<Objetivo> Objetivoes { get; set; }
        public virtual DbSet<Perspectiva> Perspectivas { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
    }
}
