//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2cmi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_Datos
    {
        public int ID { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IndicadorID { get; set; }
    
        public virtual Indicador Indicador { get; set; }
    }
}
